// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhoYMUWuF7TC91dQMv8Feo0QmCW38vos',
    appId: '1:438970553897:web:7d38e4c99603785acb6e38',
    messagingSenderId: '438970553897',
    projectId: 'telecare-platform-61005',
    authDomain: 'telecare-platform-61005.firebaseapp.com',
    storageBucket: 'telecare-platform-61005.firebasestorage.app',
    measurementId: 'G-KSYFX3XHCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaMy37auRY-lHpflkz2f-Xec3OsgHdz40',
    appId: '1:438970553897:android:54a7b3fcc7570f8bcb6e38',
    messagingSenderId: '438970553897',
    projectId: 'telecare-platform-61005',
    storageBucket: 'telecare-platform-61005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHqABaWYgwEgw6xixyJbbVHB4JPBaakc',
    appId: '1:438970553897:ios:0fb5dd7e05dbc448cb6e38',
    messagingSenderId: '438970553897',
    projectId: 'telecare-platform-61005',
    storageBucket: 'telecare-platform-61005.firebasestorage.app',
    iosClientId: '438970553897-5q29uqk43qvs2c3qrenlagoi4gf1t182.apps.googleusercontent.com',
    iosBundleId: 'com.example.telecareMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArHqABaWYgwEgw6xixyJbbVHB4JPBaakc',
    appId: '1:438970553897:ios:0fb5dd7e05dbc448cb6e38',
    messagingSenderId: '438970553897',
    projectId: 'telecare-platform-61005',
    storageBucket: 'telecare-platform-61005.firebasestorage.app',
    iosClientId: '438970553897-5q29uqk43qvs2c3qrenlagoi4gf1t182.apps.googleusercontent.com',
    iosBundleId: 'com.example.telecareMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwhoYMUWuF7TC91dQMv8Feo0QmCW38vos',
    appId: '1:438970553897:web:f215998a8c85f0d0cb6e38',
    messagingSenderId: '438970553897',
    projectId: 'telecare-platform-61005',
    authDomain: 'telecare-platform-61005.firebaseapp.com',
    storageBucket: 'telecare-platform-61005.firebasestorage.app',
    measurementId: 'G-BFQYTS9WH5',
  );
}
